CREATE TABLE domains (
domain VARCHAR(63) PRIMARY KEY,
name VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
ns1 VARCHAR(255) NOT NULL,
ns2 VARCHAR(255) NOT NULL,
ns1_ip VARCHAR(39),
ns2_ip VARCHAR(39),
registered DATE NOT NULL,
expires DATE,
updated DATE NOT NULL,
userid INT NOT NULL,
isns INT(1) DEFAULT 0,
txt VARCHAR(255),
dskey VARCHAR(255),
pgpkey VARCHAR(8192));

create table users (
userid INTEGER PRIMARY KEY,
username VARCHAR(20) NOT NULL,
password VARHCAR(32) NOT NULL,
name VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL,
country VARCHAR(2),
registered DATE NOT NULL,
verified INT NOT NULL);
